all: main

compile = g++

CC_FLAGS := -O3 -Wall

main: $(projname)a.cpp 
	$(compile) $(CC_FLAGS) Aufgabe_01_3a.cpp -o Aufgabe_01_3a
	$(compile) $(CC_FLAGS) Aufgabe_01_3b.cpp -o Aufgabe_01_3b
	$(compile) $(CC_FLAGS) Aufgabe_01_3c.cpp -o Aufgabe_01_3c

clean:
	rm -f Aufgabe_01_3

